### PR TITLE
Add Orcasound processing

### PR DESCRIPTION
**Pull request by Molkree**
This is basically a copy of the current OOI workflow with a few changes:
- because Orcasound audio is in stereo obspy creates rather weird spectrograms, it looks like it possibly appends two streams one after another because when I used it first it had 20 sec on the x-axis while recordings are ~10 sec length. I dropped it and switched to scipy for reading wav + matplotlib for plotting.
- new workflow doesn't run on schedule and instead just runs on a manual trigger (can add scheduled runs if desired).
- when run it fetches all files from the latest 'timestamp', so it might be anything between 0-6(?) hours, files are ~10 sec length.
- all files are being converted to .wav using ffmpeg.
- spectrograms are being created for each channel, no bandpass filter or decimate like with obspy. We also passed `dbscale=True, wlen=0.1` when creating OOI spectrograms, here I haven't passed anything.
- all spectrograms are being uploaded like before.
- I've added a step that stitches together all audio files into one (also uploading it).

And I've replaced `print`s with proper logging so we can see which file is being processed in real-time (it was in huge chunks of dozens of lines before, some kind of GitHub output batching I guess).

Around 5.4 hours of data yield 400 MB of spectrograms, quite a lot.

[Example run](https://github.com/Molkree/orca-action-workflow/actions/runs/937541599)
Example spectrogram (it looks like everything above 16-17 kHz can be filtered?):
live000_spectrogram

P.S. Hardcoded Bush Point for now.

### CODE REVIEW

**Comment by yosoyjay** [comment]
:+1: for adding `logging` instead of print statements.

Another thing we might want to think about is adding linting checks or actions for the repos.

**Comment by Molkree** [comment]
> Another thing we might want to think about is adding linting checks or actions for the repos.

I think I'll just run [pre-commit](https://github.com/orcasound/orca-action-workflow/blob/main/.pre-commit-config.yaml) for that, can be easily extended for linting on PRs. thanks for idea.

**Comment by valentina-s** [comment]
* the bandpass filter in OOI script was experimental (different application might need a different filter)
* wlen affects the resolution. There is some default value in scipy, so it would be good to add what it is, or adjust it if there is a better choice. @kunakl07 experimented with some spectrogram generation, so may have a suggestion what to use. If we are summing all the values in the end it might not matter, if we are having neighboring patterns, it may matter.
* For this plotting scenario, maybe a colorbar in DB would be useful. To me the nonscientist is less important, as we look at relative patterns, and for further preprocessing we may need images without the axes (though then storing the metadata is another question). Looks like it is already on a log scale by default? 
* We may also want proper timestamps (maybe at least in the name). 
* Add docstrings to the script
* Add timestamp to the wav filename

**Comment by valentina-s** [comment]
I could quickly look through all the spectrograms with an image viewer (in 6s), and spotted some boats! Individual whale calls are on the order of 3 sec, so they may be squished in the current view. You may try to test it on a day that for sure had whales.

**Comment by Molkree** [comment]
> * wlen affects the resolution. There is some default value in scipy, so it would be good to add what it is, or adjust it if there is a better choice. @kunakl07 experimented with some spectrogram generation, so may have a suggestion what to use. If we are summing all the values in the end it might not matter, if we are having neighboring patterns, it may matter.

@valentina-s, in this PR I use matplotlib for spectrogram creation, not scipy (it is only used to read wav).

`wlen` in obspy that we used for OOI was set at 0.1 which means that each FFT window would get 0.1s of data. matplotlib has a slightly different parameter `NFFT` which defines how many datapoints each window gets. Default is 256. Because our recordings are 48 kHz equivalent of OOI processing would be `NFFT=4800`. But because our recordings are only 10 seconds long it looks pretty low res, 256 is better (higher the number, lower the resolution). At the same time maybe it's easier to see patterns?

Here's some comparison with different resolutions:

`NFFT=128`, less than default, this also required to lower `noverlap` (made it 64) `The number of points of overlap between blocks. default: 128`:

live000_spectrogram_128


Default `NFFT=256`:

live000_spectrogram_256


`NFFT=512`:

live000_spectrogram_512


`NFFT=1024`:

live000_spectrogram_1024


`NFFT=2048`:

live000_spectrogram_2048


`NFFT=4096`, power of 2 less than 4800:

live000_spectrogram_4096


`NFFT=4800`:

live000_spectrogram_4800


`NFFT=8192`, power of 2 more than 4800:

live000_spectrogram_8192

**Comment by Molkree** [comment]
Adding to the above I've tested how much NFFT affects the speed.

I've ran parallel jobs with parameters as in the comment above, with all steps (including VM boot up, software install and spectrogram uploading):

image

I'd say they all are pretty close to each other, maybe only 8192 being noticeably longer.

A more honest comparison of just spectrogram creation step:
128   -- 16m 31s
256   -- 14m 4s
512   -- 16m 21s
1024 -- 14m 42s
2048 -- 15m 53s
4096 -- 17m 21s
4800 -- 17m 45s
8192 -- 21m 35s

You can find the run [here](https://github.com/Molkree/orca-action-workflow/actions/runs/955400133).

P.S. It's interesting that resolution doesn't really correlate with resulting .png size:

image

**Comment by valentina-s** [comment]
Nice comparisons! 
For the resolution you can try to do the same experiment with a time when there are more interesting sounds. 
I spotted a boat at 2021-04-13T16-55-00.000015.
Here is also a reference to a time in November when the orcas were next to Bush Point:
http://www.orcasound.net/2020/11/03/listeners-detect-j-pods-third-fall-visit-to-puget-sound/

Seems in the orcaal preprocessing either nfft 1024(matplotlib) or 2048(default in librosa) was used:
https://github.com/orcasound/orcaal-research/blob/master/src/preprocessing_script/preprocess.py
https://github.com/orcasound/orcaal/blob/master/preprocess/util.py
(I am not sure if the sample rate is the same?)

**Comment by valentina-s** [comment]
There is a trade-off between frequency resolution and time resolution, so the total size of the the spectrogram does not necessarily increase. I suspect the output also depends on the figure size setting. `plt.savefig` has an option `dpi` to increase the quality if needed.

**Comment by Molkree** [comment]
> * For this plotting scenario, maybe a colorbar in DB would be useful. To me the nonscientist is less important, as we look at relative patterns, and for further preprocessing we may need images without the axes (though then storing the metadata is another question). Looks like it is already on a log scale by default?

From docs:

> scale{'default', 'linear', 'dB'}
The scaling of the values in the spec. 'linear' is no scaling. 'dB' returns the values in dB scale. When mode is 'psd', this is dB power (10 * log10). Otherwise this is dB amplitude (20 * log10). 'default' is 'dB' if mode is 'psd' or 'magnitude' and 'linear' otherwise.

So because we use `psd` (it's default) it means that `scale` is `dB` which means it's "dB power (10 * log10)".

live000

**Comment by Molkree** [comment]
@valentina-s 

> - Add docstrings to the script
> - Add timestamp to the wav filename

Done

**Pull request merged**
